### ISSUE TITLE
Minor issues with Berkeley template

### ISSUE THREAD

**Issue by suchow** [suchow/Dissertate#37]
1. I'm seeing a text-collision issue:

![screenshot 2015-10-14 01 33 20](https://cloud.githubusercontent.com/assets/613981/10475655/b6d72184-7213-11e5-8c7d-547aafcee455.jpg)

2. What do you think about using California Gold for the chapter numbers?

![screenshot 2015-10-14 01 46 25](https://cloud.githubusercontent.com/assets/613981/10475798/724eeb9e-7215-11e5-9c3a-42cee1b5bbf2.jpg)
(See http://www.berkeley.edu/brand/img/colors/WebColor_accessible_AA_swatches.pdf)

cc @michaelpacer

**Comment by michaelpacer** [comment]
It would seem that #39 addresses these.

**Comment by michaelpacer** [comment]
@suchow  vote to close?

**Comment by Decagon** [comment]
Seems like this issue was fixed in 039d24
