### ISSUE TITLE
Harvard abstract should be double spaced

### ISSUE THREAD

**Issue by lazovich** [suchow/Dissertate#49]
According to the latest "Form of the dissertation" guidelines, the abstract should be double spaced. This isn't true in the version of the Harvard template that I have (though given I started writing in the fall I am a bit out of date now). 

See page 15 of https://www.gsas.harvard.edu/images/stories/pdfs/form%20of%20dissertation.pdf

**Comment by gregreen** [comment]
The body of the Harvard thesis should also be double-spaced, but it looks like it's only 1.2-spaced in the template. Are we supposed to uncomment this line from `dissertation.tex`?

    % \doublespacing

**Comment by lazovich** [comment]
Yes, I uncommented that line to get doublespacing in the main text, but it still leaves the abstract single spaced. I solved the abstract problem by wrapping my abstract in a \begin{doublespace} ... \end{doublespace} block.

**Comment by amyspark** [comment]
You could edit `Dissertate.cls` and add the parameter `doublespacing` to the package `setspace`.
`\RequirePackage[doublespacing]{setspace}`

**Comment by gregreen** [comment]
I address this issue in #52.

**Comment by Decagon** [comment]
Should this be closed? It looks like it's been addressed in #52.

**Comment by michaelpacer** [comment]
Yes. Issue closed.
