### ISSUE TITLE
Appendix links broken with TeX Live 2015

### ISSUE THREAD

**Issue by amyspark** [suchow/Dissertate#51]
Dissertate version: bf24d33
TeX Live version: 2015 (2015.20160320-1) (from Ubuntu Xenial)

When compiling the Harvard LaTeX version of this template, if one uses TeX Live 2015, the appendix links that appear within the TOC do not lead anywhere. The PDF viewer I am using (Okular) shows the presence of the "chapter", but it's unclickable and has no page number, although it does in the TOC.

This problem does not appear with TeX Live 2013 (when used under Ubuntu Trusty).

**Comment by stgrmks** [comment]
any fix oder workaround so far?
