### ISSUE TITLE
Amazon S3 Bucket permission denied

### ISSUE THREAD

**Issue by kimeshan** [suchow/Dissertate#56]
Clicking the Generic (Word) template, the following error is page is showed:

![screen shot 2016-07-12 at 22 09 09](https://cloud.githubusercontent.com/assets/8416897/16783759/5883ca1a-487d-11e6-8668-00d7d4f51ba4.png)

It seems like the AWS S3 Bucket permissions have not been set to allow public downloads.

**Comment by Decagon** [comment]
I can download the zip file, but all I get is a folder that has a pdf named "Guidelines" with the text "Generic Guidelines" and that's it.

**Comment by kimeshan** [comment]
@Decagon Now I get exactly the same as you. I'm closing this issue, as this is no longer an S3 bucket download issue. I will open another one regarding the contents of the zip file itself.
