### ISSUE TITLE
Anyone experiencing \textbf problems?

### ISSUE THREAD

**Issue by monicapf** [suchow/Dissertate#73]
Hi, I've just realised that trying to use \textbf{} does not compile bold typeface, at least not noticeably. Other commands such as \textit{} or \textsc{} work fine. Am I missing something? 

ps. tried with a new template document in case I had introduced some bug in my current thesis. Still doesn't work on the blank template. I use Overleaf that recently switched to V2 which compiles on XeLaTeX.

Thanks!

**Comment by monicapf** [comment]
Actually, nevermind just saw that EB Garamond does not provide a bold typeface... hence not changing anything when using \textbf or \bfseries.

**Comment by maximerischard** [comment]
The EB Garamond version on [Octavio Pardo's github](https://github.com/octaviopardo/EBGaramond12) has additional weights.

**Comment by philip-ndikum** [comment]
Is there a more up to date solution for this?
